# ------------------------------------------------------------------------------------------
# NexentaStor CSI Driver - Persistent Volume Claim cloned from another PVC
# ------------------------------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexentastor-csi-driver-pvc-nginx-dynamic-clone
spec:
  storageClassName: nexentastor-csi-driver-cs-nginx-dynamic
  dataSource:
    kind: PersistentVolumeClaim
    apiGroup: ""
    name: nexentastor-csi-driver-pvc-nginx-dynamic # pvc name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume-clone
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nexentastor-csi-driver-data-clone
  volumes:
    - name: nexentastor-csi-driver-data-clone
      persistentVolumeClaim:
        claimName: nexentastor-csi-driver-pvc-nginx-dynamic-clone
        readOnly: false
