# Service for nginx pods with dynamically storage creation using NexentaStor CSI driver
#
# $ kubectl apply -f ./examples/nginx-service-dynamic-volume.yaml
#


# --------------------------------------
# NexentaStor CSI Driver - Storage Class
# --------------------------------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nexentastor-csi-driver-cs-nginx-dynamic
provisioner: nexentastor-csi-driver.nexenta.com
#mountOptions:                 # list of options for `mount` command
#  - noatime                   #
parameters:
  #dataset: csiDriverPool/test # to overwrite "defaultDataset" in config secret
  #dataIp: 10.3.199.252        # to overwrite "defaultDataIp" in config secret
  #mountFsType: nfs            # to overwrite "defaultMountFsType" in config secret
  #mountOptions: noatime       # to overwrite "defaultMountOptions" in config secret
---


# ------------------------------------------------
# NexentaStor CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexentastor-csi-driver-pvc-nginx-dynamic
spec:
  storageClassName: nexentastor-csi-driver-cs-nginx-dynamic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---


# ---------
# Nginx pods
# ---------

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-dynamic-volume
  labels:
    app: nginx-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nexentastor-csi-driver-data
      volumes:
        - name: nexentastor-csi-driver-data
          persistentVolumeClaim:
            claimName: nexentastor-csi-driver-pvc-nginx-dynamic
            readOnly: false
---


# -----------------
# Service for nginx
# -----------------

kind: Service
apiVersion: v1
metadata:
  name: nginx-service-dynamic-volume
spec:
  selector:
    app: nginx-service
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 80
